/*
 *
 * ProjectsPage constants
 *
 */

export const SET_EXPERIENCES = 'SET_EXPERIENCES';
export const GET_EXPERIENCES = 'GET_EXPERIENCES';
export const GET_EXPERIENCE = 'GET_EXPERIENCE';
export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE';
export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const GET_PUBLIC_USER = 'GET_PUBLIC_USER';
export const SET_PUBLIC_USER = 'SET_PUBLIC_USER';
export const UPDATE_PUBLIC_USER = 'SET_PUBLIC_USER';
